> ### **Assignment 2 - Numpy Array Operations** 
>


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.append 

function2 = np.average

function3 = np.arange

function4 = np.squeeze

function5 = np.vstack




In [2]:
import numpy as np

## Function 1 - np.append
np.append function add elements to the end of an array provided that the dimensions of the elements should be same.

In [15]:
# Example 1 - working (change this)
arr1 = [1, 2, 1, 25, 26]
np.append(arr1, [24, 23, 15])


array([ 1,  2,  1, 25, 26, 24, 23, 15])

We can put lists as an element inside the array, then append it with the expected lists or any element regardless of their size.



In [ ]:
# Example 2 - working
arr2 = [[2, 4, 5], [6, 7, 8]]
np.append(arr2, [10, 12])
np.append(arr2, [10, 12, 13, 14])

When axis is specified, arrays must have the same shape.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [14, 15, 16], axis = 0)

ValueError: ignored

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Some closing comments about when to use this function.

In [1]:
# Fix
arr3 = [[2, 4, 5], [7, 8, 9]]
np.append(arr3, [[14, 15, 16], [12, 15, 16]], axis = 0)

NameError: name 'np' is not defined

In arr3, index 0 has 2 dimensions, while the element to be appended has 1 dimension, thus breaks down. To fix this, the element to be appended should have 2 dimensions as well.

## Function 2 - ???

Add some explanations

In [3]:
# Example 1 - working
avg = np.array([5,6,7,8])
np.average(avg)

6.5

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 3 - ???

Add some explanations

In [10]:
# Example 1 - working
func2=np.arange(7,19,0.5)
print(func2)

[ 7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5]


Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 4 - ???

Add some explanations

In [6]:
# Example 1 - working
arr4 = np.array([[[1,2,3],[4,5,6]]])
print(arr4)
arr_squeeze = np.squeeze(arr4)
print(arr_squeeze)

[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]


Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 5 - ???

Add some explanations

In [9]:
# Example 1 - working
arr1 = np.array([1,9,4])
arr5 = np.array([0,7,1])
v_stack = np.vstack((arr1,arr5))
print(v_stack)

[[1 9 4]
 [0 7 1]]


Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.